package ClientSide;

public enum ClientReqType {
    LOGIN,
    GETLESSONSLIST,
    GETTEACHERSLIST,
    GETUSERLESSONS,
    GETRECOMMENDLIST,
    RECOMMENDREQ,
    MINORREQLIST,
    MINORREQ,
    LEAVEREQLIST,
    LEAVEREQ,
    TEMPORARYGRADESLIST,
    OBJECTION,
}
