package ClientSide;

public enum ClientReqType {
    LOGIN,
    GETLESSONSLIST,
    GETTEACHERSLIST,
    GETUSERLESSONS,
    GETRECOMMENDLIST,
    RECOMMENDREQ,
    MINORREQLIST,
    MINORREQ,
    LEAVEREQLIST,
    LEAVEREQ,
    TEMPORARYGRADESLIST,
    OBJECTION,
    SETSTUDENTGRADEAVE,
    EDIT_EMAIL,
    EDIT_PHONE,
    SET_REC_RESULT
}
