package ServerSide;

public enum ServerReqType {
    LOGIN ,
    GETLESSONSLIST,
    GETTEACHERSLIST,
    GETUSERLESSONS,
    GETRECOMMENDLIST,
    RECOMMENDREQ,
    MINORREQLIST,
    MINORREQ,
    LEAVEREQLIST,
    LEAVEREQ,
    TEMPORARYGRADESLIST,
    OBJECTION,
    SETSTUDENTGRADEAVE,
    EDIT_EMAIL,
    EDIT_PHONE
}
