package Pages;

public enum PanelType {
    LOGINPAGE,
    STUDENTMAINPAGE,
    TEACHERMAINPAGE,
    LESSONSLISTPAGE,
    TEACHERSLISTPAGE,
    WEEKLYPLANPAGE,
    EXAMSLISTPAGE,
    STUDENTRECREQPAGE,
    STUDYEVIDENCEREQPAGE,
    MINORREQPAGE,
    LEAVEREQPAGE,
    TEMPORARYGRADELISTPAGE,
    STUDENT_EDU_STATUS_PAGE,
    STUDENT_PROFILE_PAGE,
    TEACHER_REC_REQ_PAGE,
    TEACHER_TEMPORARY_GRADES_PAGE
}
