package Pages;

public enum PanelType {
    LOGINPAGE,
    STUDENTMAINPAGE,
    TEACHERMAINPAGE,
    LESSONSLISTPAGE,
    TEACHERSLISTPAGE,
    WEEKLYPLANPAGE,
    EXAMSLISTPAGE,
    STUDENTRECREQPAGE,
    STUDYEVIDENCEREQPAGE,
    MINORREQPAGE,
    LEAVEREQPAGE,
    TEMPORARYGRADELISTPAGE,
    STUDENT_EDU_STATUS_PAGE
}
